variable "ami" {}
variable "instance_type" {}
variable "security_groups" {}
#variable "public_subnet_a" {}
variable "private_subnet_a" {}
variable "private_subnet_b" {}
variable "key_pair" {}
variable "userdata_1" {}
variable "userdata_2" {}